### ISSUE TITLE
Plotly

### ISSUE THREAD

**Issue by snowman2** [erdc-cm/tethysapp-streamflow_prediction_tool#12]
Replace plots using plotly.

**Comment by msouff** [comment]
I was playing with this, but I don't have time to finish it, at least not know. There's tons of code to replace to make this change. Here is how the graph looks with plotly though:

https://plot.ly/~msouff/37.embed

`<div>
    <a href="https://plot.ly/~msouff/37/?share_key=yDOL14rtkgexv3KzqzKtwV" target="_blank" title="api-slider-example" style="display: block; text-align: center;"><img src="https://plot.ly/~msouff/37.png?share_key=yDOL14rtkgexv3KzqzKtwV" alt="api-slider-example" style="max-width: 100%;width: 600px;"  width="600" onerror="this.onerror=null;this.src='https://plot.ly/404.png';" /></a>
</div>`

**Comment by snowman2** [comment]
@msouff, that looks great! Just so you are aware, I moved the historical data to a separate plot in the most recent version. So, that should make things much simpler.
