### ISSUE TITLE
Main DB won't initialize

### ISSUE THREAD

**Issue by msouff** [erdc-cm/tethysapp-streamflow_prediction_tool#23]
The main db won't initialize under the new settings that replaced the mainsettings model function for a custom setting. The problem may be the init_stores.py, which I noticed has not been updated to reflect the custom settings change. I tried a few things like using the app.get_custom_setting or just commenting out the line of code that references the main settings but that did not work.

The app cannot be installed successfully without fixing this.

**Comment by snowman2** [comment]
@msouff, I haven't tested initializing the db. I will look at that and see if I can get it fixed. Thanks!
